[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    sparkfun/SparkFun VL53L5CX Arduino Library
    sparkfun/SparkFun VL53L1X 4m Laser Distance Sensor